spring:
  application:
    name: common-bank

#eureka:
#    client:
#        serviceUrl:
#          defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#         prefer-ip-address: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
