server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: amigo-wallet-service
            uri: lb://amigo-wallet-service
            predicates:
              - Path=/amigo-wallet/**
            filters:
              - AuthenticationFilter
          - id: common-bank
            uri: lb://common-bank
            predicates:
              - Path=/common-bank/**
            filters:
              - AuthenticationFilter
          - id: identity-service
            uri: lb://identity-service
            predicates:
              - Path=/auth/**
          - id: amigo-wallet-user
            uri: lb://amigo-wallet-user
            predicates:
              - Path=/user-service/**
            filters:
              - AuthenticationFilter

